#!/bin/bash
# autogenerated eqnx run script for:
# - eqnx: ./eqnx
# - prog: esx/calendar.esx
# - conf: config.lua
# - psrc: plugins/
# - root: $HOME

HERE="/home/hugo/code/eqnx"
EQNX="$(which "./eqnx" || echo "$HERE/./eqnx")"
PROG="$HERE/esx/calendar.esx"
CONF="$HERE/config.lua"
PSRC="$HERE/plugins/"

# Change cwd to root
cd "$HOME"

# Run
"$EQNX" -p "$PROG" -c "$CONF" -s "$PSRC"
