.\" Manpage for eqnx.
.\" Contact me@hugocoto.com to correct errors or typos (or create a pr).
.TH eqnx 1 "2 Feb 2026" "0.1" "eqnx man page"
.SH NAME
eqnx \- Integration ecosystem for text-based graphical interfaces.
.SH SYNOPSIS
.B eqnx
[ \fB\-h\fR | \fB\-\-help\fR ]
[ \fB\-v\fR | \fB\-\-version\fR ]
\fB\-p\fR \fIP\fR | \fB\-\-plugin\fR \fIP\fR
.SH DESCRIPTION
This tool provides the structural foundation for various software extensions to
seamlessly coexist within a single visual space. Users can program autonomous
components that not only display information on a character matrix but also act
as orchestrators for other sub-components. This visual hierarchy grants
developers absolute control over the interface layout and interaction
distribution, ensuring that every element operates in a fluid and coordinated
manner.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Show this help.
.TP
\fB\-v\fR, \fB\-\-version\fR
Show version.
.TP
\fB\-p\fR \fIP\fR, \fB\-\-program\fR \fIP\fR
ESX Program to be loaded.
.SH AUTHOR
Hugo Coto (me@hugocoto.com)
