.\" Manpage for eqnx.
.\" Contact me@hugocoto.com to correct errors or typos (or create a pr).
.TH eqnx 1 "22 Dec 2025" "0.1" "eqnx man page"
.SH NAME
eqnx \- Hugo's toolchain environment.
.SH SYNOPSIS
eqnx [OPTIONS]
.SH DESCRIPTION
eqnx description here.
.SH OPTIONS
eqnx options here.
.\" .SH SEE ALSO
.\" vim(1), emacs(1)
.SH AUTHOR
Hugo Coto (me@hugocoto.com)
