#!/bin/bash
# autogenerated eqnx run script for:
# - eqnx: ../eqnx
# - prog: ztemplate.esx
# - conf: ../config.lua
# - psrc: ./zig-out/lib/
# - root: $HOME

# ADD (manually): rebuild
zig build || exit 1
# -----------------------

HERE="/home/hugo/code/eqnx/zig"
EQNX="$(which "../eqnx" || echo "$HERE/../eqnx")"
PROG="$HERE/ztemplate.esx"
CONF="$HERE/../config.lua"
PSRC="$HERE/./zig-out/lib/"

# Change cwd to root
cd "$HOME"

# Run
"$EQNX" -p "$PROG" -c "$CONF" -s "$PSRC"
