#!/bin/bash
# autogenerated eqnx run script for:
# - eqnx: ./eqnx
# - prog: rterminal/template.esx
# - conf: config.lua
# - psrc: rterminal/target/debug/
# - root: $HOME

HERE="/home/hugo/code/eqnx"
EQNX="$(which "./eqnx" || echo "$HERE/./eqnx")"
PROG="$HERE/rterminal/template.esx"
CONF="$HERE/config.lua"
PSRC="$HERE/rterminal/target/debug/"

# ADD: cargo rebuild
cd "$HERE/rterminal" && cargo build

# Change cwd to root
cd "$HOME"

# Run
"$EQNX" -p "$PROG" -c "$CONF" -s "$PSRC"
