// rterminal – minimal VT220/xterm terminal emulator plugin for eqnx
// Architecture: single Term struct holds all state; no scattered globals.
// Modelled after st (suckless terminal): simple, correct, one job.
#![allow(unsafe_op_in_unsafe_fn, clippy::needless_range_loop)]

// ──────────────────────────────────────────────────────────────────────────────
// eqnx bindings (generated by bindgen at build time)
// ──────────────────────────────────────────────────────────────────────────────
#[allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    unnecessary_transmutes
)]
mod eqnx {
    include!("../bindings/eqnx.rs");
}

// ──────────────────────────────────────────────────────────────────────────────
// Color constants
// ──────────────────────────────────────────────────────────────────────────────

const ANSI_COLORS: [u32; 8] = [
    eqnx::BLACK,
    eqnx::RED,
    eqnx::GREEN,
    eqnx::YELLOW,
    eqnx::BLUE,
    eqnx::MAGENTA,
    eqnx::CYAN,
    eqnx::WHITE,
];

// Bright variants – no separate bright palette in this theme; bright-black → GRAY.
const BRIGHT_COLORS: [u32; 8] = [
    eqnx::GRAY,
    eqnx::RED,
    eqnx::GREEN,
    eqnx::YELLOW,
    eqnx::BLUE,
    eqnx::MAGENTA,
    eqnx::CYAN,
    eqnx::WHITE,
];

// 6-level cube component values for the 256-colour palette
const CUBE6: [u32; 6] = [0, 95, 135, 175, 215, 255];

fn build_palette() -> [u32; 256] {
    let mut p = [0u32; 256];
    for i in 0..8 {
        p[i] = ANSI_COLORS[i];
    }
    for i in 0..8 {
        p[8 + i] = BRIGHT_COLORS[i];
    }
    let mut idx = 16usize;
    for r in 0..6usize {
        for g in 0..6usize {
            for b in 0..6usize {
                p[idx] = 0xFF00_0000 | (CUBE6[r] << 16) | (CUBE6[g] << 8) | CUBE6[b];
                idx += 1;
            }
        }
    }
    for i in 0..24usize {
        let v = (8 + i * 10).min(255) as u32;
        p[232 + i] = 0xFF00_0000 | (v << 16) | (v << 8) | v;
    }
    p
}

// ──────────────────────────────────────────────────────────────────────────────
// DEC Special Graphics (G1 charset).  Index = byte - 0x60.
// ──────────────────────────────────────────────────────────────────────────────

const DEC_SPECIAL: [u32; 31] = [
    0x25C6, 0x2592, 0x2409, 0x240C, 0x240D, 0x240A, 0x00B0, 0x00B1, 0x2424, 0x240B, 0x2518, 0x2510,
    0x250C, 0x2514, 0x253C, 0x23BA, 0x23BB, 0x2500, 0x23BC, 0x23BD, 0x251C, 0x2524, 0x2534, 0x252C,
    0x2502, 0x2264, 0x2265, 0x03C0, 0x2260, 0x00A3, 0x00B7,
];

// East Asian Wide character detection (most common ranges)
const fn is_wide(cp: u32) -> bool {
    cp >= 0x1100 && cp <= 0x115F   // Hangul Jamo
    || cp >= 0x2E80 && cp <= 0x9FFF  // CJK block
    || cp >= 0xAC00 && cp <= 0xD7AF  // Hangul Syllables
    || cp >= 0xF900 && cp <= 0xFAFF  // CJK Compat
    || cp >= 0xFF01 && cp <= 0xFF60  // Fullwidth
    || cp >= 0xFFE0 && cp <= 0xFFE6
    || cp >= 0x1F000 && cp <= 0x1FFFF // Supplementary
}

// ──────────────────────────────────────────────────────────────────────────────
// Cell – one terminal grid position
// ──────────────────────────────────────────────────────────────────────────────

/// Flags stored in `Cell::flags`
const CELL_WIDE_RIGHT: u8 = 1 << 0; // right half of a 2-column character

#[derive(Copy, Clone, PartialEq)]
struct Cell {
    ch: u32, // Unicode codepoint; 0 = empty / wide continuation
    fg: u32, // foreground color (ARGB)
    bg: u32, // background color (ARGB)
    flags: u8,
}

impl Cell {
    const fn blank(fg: u32, bg: u32) -> Self {
        Cell {
            ch: b' ' as u32,
            fg,
            bg,
            flags: 0,
        }
    }
    const DEFAULT: Self = Cell::blank(eqnx::FOREGROUND, eqnx::BACKGROUND);
}

// ──────────────────────────────────────────────────────────────────────────────
// Attr – current drawing attribute state
// Stored separately from Cell so the cursor can carry its own copy (VT spec).
// ──────────────────────────────────────────────────────────────────────────────

const ATTR_BOLD: u8 = 1 << 0;
const ATTR_REVERSE: u8 = 1 << 1;
#[allow(dead_code)]
const ATTR_ITALIC: u8 = 1 << 2;
#[allow(dead_code)]
const ATTR_UNDERLINE: u8 = 1 << 3;

#[derive(Copy, Clone)]
struct Attr {
    fg: u32,
    bg: u32,
    flags: u8,
}

impl Attr {
    const DEFAULT: Self = Attr {
        fg: eqnx::FOREGROUND,
        bg: eqnx::BACKGROUND,
        flags: 0,
    };

    fn is_bold(self) -> bool {
        self.flags & ATTR_BOLD != 0
    }
    fn is_reverse(self) -> bool {
        self.flags & ATTR_REVERSE != 0
    }

    /// Resolve the actual fg/bg colours for rendering, applying reverse and bold.
    fn resolve(self) -> (u32, u32) {
        let (fg, bg) = if self.is_reverse() {
            (self.bg, self.fg)
        } else {
            (self.fg, self.bg)
        };
        let fg = if self.is_bold() { boost(fg) } else { fg };
        (fg, bg)
    }

    /// Produce a Cell from this Attr + a codepoint.
    fn make_cell(self, ch: u32) -> Cell {
        let (fg, bg) = self.resolve();
        Cell {
            ch,
            fg,
            bg,
            flags: 0,
        }
    }
}

/// Boost RGB brightness ~30% for bold text.
/// Applied once at write time so cells are self-contained.
fn boost(c: u32) -> u32 {
    let r = (c >> 16) & 0xFF;
    let g = (c >> 8) & 0xFF;
    let b = c & 0xFF;
    let bst = |v: u32| -> u32 { (v + (255 - v) * 77 / 256).min(255) };
    (c & 0xFF00_0000) | (bst(r) << 16) | (bst(g) << 8) | bst(b)
}

// ──────────────────────────────────────────────────────────────────────────────
// Cursor
// ──────────────────────────────────────────────────────────────────────────────

#[derive(Copy, Clone)]
struct Cursor {
    x: usize,
    y: usize,
    #[allow(dead_code)]
    attr: Attr, // saved with cursor per VT spec; not yet wired into SGR restore
    pending_wrap: bool,
    charset: u8, // G0: 0=ASCII, 1=DEC Special Graphics
}

impl Cursor {
    const DEFAULT: Self = Cursor {
        x: 0,
        y: 0,
        attr: Attr::DEFAULT,
        pending_wrap: false,
        charset: 0,
    };
}

// ──────────────────────────────────────────────────────────────────────────────
// Parser – VT escape sequence state machine
//
// Parameters are accumulated as integers as we go (digit by digit), not as
// raw bytes requiring a second parse pass.  This mirrors what st does.
// ──────────────────────────────────────────────────────────────────────────────

#[derive(Copy, Clone, PartialEq)]
enum PState {
    Ground,
    Esc,
    EscInter(u8), // ESC followed by one intermediate byte
    Csi,
    OscStr,
    OscMaybeSt, // saw ESC inside OSC; next byte decides if it's ST ('\\')
}

struct Parser {
    state: PState,
    params: [i32; 16], // already-parsed integer parameters
    nparams: usize,
    cur: i32,        // digit accumulator for current parameter
    inter: u8,       // CSI intermediate byte (0 = none)
    priv_mode: bool, // '?' prefix in CSI
    osc: Vec<u8>,    // OSC string payload (usually short)
    // UTF-8 decoder state
    utf8_rem: u8,
    utf8_cp: u32,
}

impl Parser {
    fn new() -> Self {
        Parser {
            state: PState::Ground,
            params: [0; 16],
            nparams: 0,
            cur: 0,
            inter: 0,
            priv_mode: false,
            osc: Vec::new(),
            utf8_rem: 0,
            utf8_cp: 0,
        }
    }

    fn reset(&mut self) {
        self.state = PState::Ground;
        self.nparams = 0;
        self.cur = 0;
        self.inter = 0;
        self.priv_mode = false;
        self.osc.clear();
        self.utf8_rem = 0;
        self.utf8_cp = 0;
    }

    /// Commit the currently-accumulating parameter and start a new one.
    fn commit_param(&mut self) {
        if self.nparams < 16 {
            self.params[self.nparams] = self.cur;
            self.nparams += 1;
        }
        self.cur = 0;
    }

    /// Get parameter n, or `default` if not present.  Parameters are 1-indexed
    /// in the VT spec; index here is 0-based.
    #[allow(dead_code)]
    fn p(&self, n: usize, default: i32) -> i32 {
        // Commit current accumulator virtually without mutating self.
        let total = if self.nparams < 16 {
            self.nparams + 1
        } else {
            self.nparams
        };
        if n < total {
            if n == self.nparams {
                self.cur
            } else {
                self.params[n]
            }
        } else {
            default
        }
    }

    /// Same as p() but treats 0 as the default.
    #[allow(dead_code)]
    fn p_or(&self, n: usize, default: i32) -> i32 {
        let v = self.p(n, default);
        if v == 0 { default } else { v }
    }

    /// Feed one byte into the UTF-8 decoder.  Returns Some(codepoint) when complete.
    fn utf8(&mut self, b: u8) -> Option<u32> {
        if self.utf8_rem == 0 {
            if b & 0x80 == 0 {
                return Some(b as u32);
            }
            if b & 0xE0 == 0xC0 {
                self.utf8_cp = (b & 0x1F) as u32;
                self.utf8_rem = 1;
            } else if b & 0xF0 == 0xE0 {
                self.utf8_cp = (b & 0x0F) as u32;
                self.utf8_rem = 2;
            } else if b & 0xF8 == 0xF0 {
                self.utf8_cp = (b & 0x07) as u32;
                self.utf8_rem = 3;
            }
            // else: invalid lead byte, drop
            return None;
        }
        if b & 0xC0 != 0x80 {
            // Not a continuation; reset decoder and drop
            self.utf8_rem = 0;
            self.utf8_cp = 0;
            return None;
        }
        self.utf8_cp = (self.utf8_cp << 6) | (b & 0x3F) as u32;
        self.utf8_rem -= 1;
        if self.utf8_rem == 0 {
            let cp = self.utf8_cp;
            self.utf8_cp = 0;
            // Reject surrogates and out-of-range
            if cp > 0x10FFFF || (cp >= 0xD800 && cp <= 0xDFFF) {
                return None;
            }
            return Some(cp);
        }
        None
    }
}

// ──────────────────────────────────────────────────────────────────────────────
// Modes – DEC/ANSI mode flags
// ──────────────────────────────────────────────────────────────────────────────

#[derive(Clone)]
struct Modes {
    wrap: bool,
    cursor_visible: bool,
    app_keypad: bool,
    app_cursor: bool, // DECCKM – application cursor keys
    mouse: bool,
    cursor_shape: u8, // 0=block, 3=underline, 5=bar
}

impl Modes {
    fn new() -> Self {
        Modes {
            wrap: true,
            cursor_visible: true,
            app_keypad: false,
            app_cursor: false,
            mouse: false,
            cursor_shape: 0,
        }
    }
}

// ──────────────────────────────────────────────────────────────────────────────
// Term – the complete terminal state
// ──────────────────────────────────────────────────────────────────────────────

struct Term {
    rows: usize,
    cols: usize,

    // Screen buffers: index 0 = normal, 1 = alternate.
    // Each is a flat Vec of rows*cols cells; cell at (r,c) = buf[r * cols + c].
    screens: [Vec<Cell>; 2],
    alt: usize, // active screen index (0 or 1)

    // Cursors: one saved per screen (mirrors what st does).
    cursor: [Cursor; 2],

    // Scroll region (0-indexed, both inclusive)
    scroll_top: usize,
    scroll_bottom: usize,

    // Current SGR drawing attributes (used by write_cell)
    attr: Attr,

    // Parser
    parser: Parser,

    // DEC/ANSI mode flags
    modes: Modes,

    // Per-column tab stops
    tab_stops: Vec<bool>,

    // 256-colour palette (built once at creation)
    palette: [u32; 256],

    // Visual bell pending
    bell: bool,

    // PTY master handle
    pty: Master,
}

extern crate pty;
use pty::fork::*;
use std::{
    env,
    io::Write,
    mem,
    os::fd::AsRawFd,
    process::Command,
    ptr,
};

impl Term {
    fn new(rows: usize, cols: usize, pty: Master) -> Box<Self> {
        let rows = rows.max(1);
        let cols = cols.max(1);
        let blank = Cell::DEFAULT;
        let screens = [vec![blank; rows * cols], vec![blank; rows * cols]];
        let mut tab_stops = vec![false; cols];
        for c in (0..cols).step_by(8) {
            tab_stops[c] = true;
        }

        Box::new(Term {
            rows,
            cols,
            screens,
            alt: 0,
            cursor: [Cursor::DEFAULT; 2],
            scroll_top: 0,
            scroll_bottom: rows.saturating_sub(1),
            attr: Attr::DEFAULT,
            parser: Parser::new(),
            modes: Modes::new(),
            tab_stops,
            palette: build_palette(),
            bell: false,
            pty,
        })
    }

    // ── Screen access ──────────────────────────────────────────────────────

    #[allow(dead_code)]
    fn screen(&self) -> &Vec<Cell> {
        &self.screens[self.alt]
    }
    #[allow(dead_code)]
    fn screen_mut(&mut self) -> &mut Vec<Cell> {
        &mut self.screens[self.alt]
    }

    #[inline]
    fn cell(&self, r: usize, c: usize) -> &Cell {
        &self.screens[self.alt][r * self.cols + c]
    }
    #[inline]
    fn cell_mut(&mut self, r: usize, c: usize) -> &mut Cell {
        let cols = self.cols;
        &mut self.screens[self.alt][r * cols + c]
    }

    // ── Cursor access ──────────────────────────────────────────────────────

    #[inline]
    fn cur(&self) -> &Cursor {
        &self.cursor[self.alt]
    }
    #[inline]
    fn cur_mut(&mut self) -> &mut Cursor {
        &mut self.cursor[self.alt]
    }

    // ── Cell writing ───────────────────────────────────────────────────────

    /// Write a codepoint at (row, col) with the *current* Term::attr.
    /// Bold boost is applied here so the cell is self-contained.
    fn write_cell(&mut self, row: usize, col: usize, ch: u32) {
        debug_assert!(row < self.rows && col < self.cols);
        let cell = self.attr.make_cell(ch);
        let cols = self.cols;
        self.screens[self.alt][row * cols + col] = cell;
    }

    /// Fill a cell range [col_start, col_end) on row with blank cells using
    /// default colours (not current attr).  Used for erasing.
    fn erase_cols(&mut self, row: usize, col_start: usize, col_end: usize) {
        let cols = self.cols;
        let end = col_end.min(cols);
        let (fg, bg) = (self.attr.fg, self.attr.bg);
        // Use attr bg for erase (standard terminal behaviour): when app resets
        // SGR, erasing uses the default bg.  We use the *current* bg so that
        // apps that set a bg colour and then erase get the right colour.
        for c in col_start..end {
            self.screens[self.alt][row * cols + c] = Cell::blank(eqnx::FOREGROUND, bg);
        }
        // Silence unused-variable warning
        let _ = fg;
    }

    fn erase_row(&mut self, row: usize) {
        let cols = self.cols;
        self.erase_cols(row, 0, cols);
    }

    fn erase_screen(&mut self) {
        for r in 0..self.rows {
            self.erase_row(r);
        }
    }

    // ── Scrolling ──────────────────────────────────────────────────────────

    /// Scroll lines [orig, scroll_bottom] up by n, clearing freed lines at bottom.
    fn scroll_up(&mut self, orig: usize, n: usize) {
        let top = self.scroll_top;
        let bottom = self.scroll_bottom;
        if orig < top || orig > bottom {
            return;
        }
        let count = n.min(bottom + 1 - orig);
        let cols = self.cols;
        let scr = &mut self.screens[self.alt];
        for row in orig..=bottom - count {
            let src = (row + count) * cols;
            let dst = row * cols;
            scr.copy_within(src..src + cols, dst);
        }
        // Clear the freed lines at the bottom with default bg
        let bg = self.attr.bg;
        let scr = &mut self.screens[self.alt];
        for row in (bottom + 1 - count)..=bottom {
            for c in 0..cols {
                scr[row * cols + c] = Cell::blank(eqnx::FOREGROUND, bg);
            }
        }
    }

    /// Scroll lines [orig, scroll_bottom] down by n, clearing freed lines at top.
    fn scroll_down(&mut self, orig: usize, n: usize) {
        let top = self.scroll_top;
        let bottom = self.scroll_bottom;
        if orig < top || orig > bottom {
            return;
        }
        let count = n.min(bottom + 1 - orig);
        let cols = self.cols;
        let scr = &mut self.screens[self.alt];
        for row in (orig..=bottom - count).rev() {
            let src = row * cols;
            let dst = (row + count) * cols;
            scr.copy_within(src..src + cols, dst);
        }
        // Clear freed lines at the top
        let bg = self.attr.bg;
        let scr = &mut self.screens[self.alt];
        for row in orig..orig + count {
            for c in 0..cols {
                scr[row * cols + c] = Cell::blank(eqnx::FOREGROUND, bg);
            }
        }
    }

    // ── Cursor movement ────────────────────────────────────────────────────

    /// Move cursor to (x, y), clamped, resetting pending_wrap.
    fn move_to(&mut self, x: usize, y: usize) {
        let cols = self.cols;
        let rows = self.rows;
        let c = self.cur_mut();
        c.x = x.clamp(0, cols.saturating_sub(1));
        c.y = y.clamp(0, rows.saturating_sub(1));
        c.pending_wrap = false;
    }

    fn move_x(&mut self, x: usize) {
        let y = self.cur().y;
        self.move_to(x, y);
    }
    fn move_y(&mut self, y: usize) {
        let x = self.cur().x;
        self.move_to(x, y);
    }

    /// Clamp cursor to current dimensions (used after resize).
    fn clamp_cursor(&mut self) {
        let (rows, cols) = (self.rows, self.cols);
        let c = self.cur_mut();
        c.x = c.x.min(cols.saturating_sub(1));
        c.y = c.y.min(rows.saturating_sub(1));
        c.pending_wrap = false;
    }

    // ── Linefeed ───────────────────────────────────────────────────────────

    fn do_lf(&mut self) {
        let cy = self.cur().y;
        if cy == self.scroll_bottom {
            // At scroll region bottom: scroll the region up, cursor stays
            self.scroll_up(self.scroll_top, 1);
        } else if cy < self.rows.saturating_sub(1) {
            // Not at last screen row: advance
            self.cur_mut().y = cy + 1;
        }
        // else: at last screen row but outside scroll region → do nothing
        self.cur_mut().pending_wrap = false;
    }

    // ── Resize ─────────────────────────────────────────────────────────────

    fn resize(&mut self, rows: usize, cols: usize) {
        let rows = rows.max(1);
        let cols = cols.max(1);

        // Rebuild both screen buffers with new dimensions, preserving content.
        for s in 0..2usize {
            let mut new_buf = vec![Cell::DEFAULT; rows * cols];
            let copy_rows = self.rows.min(rows);
            let copy_cols = self.cols.min(cols);
            for r in 0..copy_rows {
                for c in 0..copy_cols {
                    new_buf[r * cols + c] = self.screens[s][r * self.cols + c];
                }
            }
            self.screens[s] = new_buf;
        }

        // Resize tab stops
        self.tab_stops.resize(cols, false);
        // Re-set any new columns that should be tab stops (every 8)
        for c in self.cols..cols {
            self.tab_stops[c] = c % 8 == 0;
        }

        self.rows = rows;
        self.cols = cols;
        self.scroll_top = 0;
        self.scroll_bottom = rows.saturating_sub(1);

        // Clamp both cursors
        for i in 0..2usize {
            self.cursor[i].x = self.cursor[i].x.min(cols.saturating_sub(1));
            self.cursor[i].y = self.cursor[i].y.min(rows.saturating_sub(1));
            self.cursor[i].pending_wrap = false;
        }
    }

    // ── Full reset (RIS / startup) ─────────────────────────────────────────

    fn full_reset(&mut self) {
        let (rows, cols) = (self.rows, self.cols);
        let blank = Cell::DEFAULT;
        for s in 0..2 {
            self.screens[s].fill(blank);
        }
        self.alt = 0;
        self.cursor = [Cursor::DEFAULT; 2];
        self.scroll_top = 0;
        self.scroll_bottom = rows.saturating_sub(1);
        self.attr = Attr::DEFAULT;
        self.parser.reset();
        self.modes = Modes::new();
        self.tab_stops.fill(false);
        for c in (0..cols).step_by(8) {
            self.tab_stops[c] = true;
        }
        self.bell = false;
    }

    // ── Character placement ────────────────────────────────────────────────
    //
    // Pending-wrap ("last column flag") logic:
    //   After writing to column cols-1, we set pending_wrap = true instead
    //   of immediately advancing.  On the NEXT printable character, we wrap
    //   first.  This is the correct VT220 behaviour that makes vim, mc, etc.
    //   draw correctly.

    fn put_char(&mut self, cp: u32) {
        // Determine column width
        let wide = self.cur().charset == 0 && is_wide(cp);
        let width = if wide { 2 } else { 1 };

        // Apply pending wrap before writing
        if self.cur().pending_wrap && self.modes.wrap {
            let cy = self.cur().y;
            self.cur_mut().x = 0;
            // Perform the linefeed (may scroll)
            if cy == self.scroll_bottom {
                self.scroll_up(self.scroll_top, 1);
                // cursor stays at scroll_bottom, x already 0
            } else {
                self.cur_mut().y = cy + 1;
            }
            self.cur_mut().pending_wrap = false;
        } else {
            self.cur_mut().pending_wrap = false;
        }

        let col = self.cur().x;
        let row = self.cur().y;

        if col >= self.cols {
            return;
        }

        // For wide chars that would straddle the right edge: pad + wrap
        if wide && col + 1 >= self.cols {
            if self.modes.wrap {
                // Write a space as padding at the edge, then wrap
                self.write_cell(row, col, b' ' as u32);
                let cy = self.cur().y;
                self.cur_mut().x = 0;
                if cy == self.scroll_bottom {
                    self.scroll_up(self.scroll_top, 1);
                } else {
                    self.cur_mut().y = cy + 1;
                }
                // Now write the wide char at col 0 of the new line
                let row2 = self.cur().y;
                self.write_cell(row2, 0, cp);
                if self.cols > 1 {
                    let mut cont = self.cell(row2, 0).clone();
                    cont.ch = 0;
                    cont.flags |= CELL_WIDE_RIGHT;
                    *self.cell_mut(row2, 1) = cont;
                    self.cur_mut().x = if self.cols > 2 { 2 } else { self.cols - 1 };
                } else {
                    self.cur_mut().x = 0;
                }
                self.cur_mut().pending_wrap = self.cur().x + 1 >= self.cols;
            }
            return;
        }

        // Normal write
        self.write_cell(row, col, cp);

        if wide && col + 1 < self.cols {
            // Fill the right-half continuation cell
            let mut cont = *self.cell(row, col);
            cont.ch = 0;
            cont.flags |= CELL_WIDE_RIGHT;
            *self.cell_mut(row, col + 1) = cont;
        }

        // Advance cursor
        let next = col + width;
        if next >= self.cols {
            // Set pending_wrap; keep cursor at last column
            self.cur_mut().x = self.cols - 1;
            self.cur_mut().pending_wrap = self.modes.wrap;
        } else {
            self.cur_mut().x = next;
        }
    }

    // ── SGR ───────────────────────────────────────────────────────────────

    fn apply_sgr(&mut self) {
        // Commit trailing parameter
        let n_committed = self.parser.nparams;
        let params_committed = self.parser.params;
        let last = self.parser.cur;

        // Build a local view: committed params + the current accumulator
        let mut args = [0i32; 17];
        for i in 0..n_committed {
            args[i] = params_committed[i];
        }
        args[n_committed] = last;
        let count = n_committed + 1;

        let mut i = 0usize;
        while i < count {
            match args[i] {
                0 => {
                    self.attr = Attr::DEFAULT;
                }
                1 => {
                    self.attr.flags |= ATTR_BOLD;
                }
                2 | 3 | 4 | 5 | 6 => {} // dim/italic/underline/blink – skip
                7 => {
                    self.attr.flags |= ATTR_REVERSE;
                }
                22 => {
                    self.attr.flags &= !ATTR_BOLD;
                }
                23 | 24 | 25 => {}
                27 => {
                    self.attr.flags &= !ATTR_REVERSE;
                }
                // Standard fg
                30..=37 => {
                    self.attr.fg = ANSI_COLORS[(args[i] - 30) as usize];
                }
                38 => {
                    if i + 2 < count && args[i + 1] == 5 {
                        self.attr.fg = self.palette[args[i + 2].clamp(0, 255) as usize];
                        i += 2;
                    } else if i + 4 < count && args[i + 1] == 2 {
                        let (r, g, b) = (
                            args[i + 2].clamp(0, 255) as u32,
                            args[i + 3].clamp(0, 255) as u32,
                            args[i + 4].clamp(0, 255) as u32,
                        );
                        self.attr.fg = 0xFF000000 | (r << 16) | (g << 8) | b;
                        i += 4;
                    }
                }
                39 => {
                    self.attr.fg = eqnx::FOREGROUND;
                }
                // Standard bg
                40..=47 => {
                    self.attr.bg = ANSI_COLORS[(args[i] - 40) as usize];
                }
                48 => {
                    if i + 2 < count && args[i + 1] == 5 {
                        self.attr.bg = self.palette[args[i + 2].clamp(0, 255) as usize];
                        i += 2;
                    } else if i + 4 < count && args[i + 1] == 2 {
                        let (r, g, b) = (
                            args[i + 2].clamp(0, 255) as u32,
                            args[i + 3].clamp(0, 255) as u32,
                            args[i + 4].clamp(0, 255) as u32,
                        );
                        self.attr.bg = 0xFF000000 | (r << 16) | (g << 8) | b;
                        i += 4;
                    }
                }
                49 => {
                    self.attr.bg = eqnx::BACKGROUND;
                }
                // Bright fg/bg
                90..=97 => {
                    self.attr.fg = BRIGHT_COLORS[(args[i] - 90) as usize];
                }
                100..=107 => {
                    self.attr.bg = BRIGHT_COLORS[(args[i] - 100) as usize];
                }
                _ => {}
            }
            i += 1;
        }
    }

    // ── CSI dispatch ──────────────────────────────────────────────────────

    fn execute_csi(&mut self, final_byte: u8) {
        let inter = self.parser.inter;
        let priv_mode = self.parser.priv_mode;

        // Commit the trailing parameter so p() reads it
        let nparams_before = self.parser.nparams;
        let cur_before = self.parser.cur;
        self.parser.params[self.parser.nparams.min(15)] = self.parser.cur;
        // Don't increment nparams permanently here; use the helper below.

        // Convenience helper that reads committed+current params
        // We define a local closure capturing the parser state.
        // NOTE: Rust borrow rules prevent borrowing self.parser inside a method
        // that also mutates self.  We copy the params out.
        let mut params = [0i32; 17];
        for i in 0..nparams_before {
            params[i] = self.parser.params[i];
        }
        params[nparams_before] = cur_before;
        let count = nparams_before + 1;

        let p = |n: usize, def: i32| -> i32 {
            if n < count && params[n] != 0 {
                params[n]
            } else {
                def
            }
        };
        // p0 = get param n with 0 as default (for cases where 0 is valid)
        let p0 = |n: usize, def: i32| -> i32 { if n < count { params[n] } else { def } };

        match (inter, priv_mode, final_byte) {
            // ── Cursor movement ──────────────────────────────────────────
            // CUU/CUD clamp to screen edges (row 0 / last row), NOT scroll region.
            // Only IND (ESC D) and RI (ESC M) interact with the scroll region.
            (0, false, b'A') => {
                let n = p(0, 1) as usize;
                let y = self.cur().y.saturating_sub(n);
                self.move_y(y);
            }
            (0, false, b'B') => {
                let n = p(0, 1) as usize;
                let y = (self.cur().y + n).min(self.rows.saturating_sub(1));
                self.move_y(y);
            }
            (0, false, b'C') => {
                let n = p(0, 1) as usize;
                let x = (self.cur().x + n).min(self.cols.saturating_sub(1));
                self.move_x(x);
            }
            (0, false, b'D') => {
                let n = p(0, 1) as usize;
                let x = self.cur().x.saturating_sub(n);
                self.move_x(x);
            }
            (0, false, b'H') | (0, false, b'f') => {
                let row = (p(0, 1) - 1).clamp(0, self.rows as i32 - 1) as usize;
                let col = (p(1, 1) - 1).clamp(0, self.cols as i32 - 1) as usize;
                self.move_to(col, row);
            }
            (0, false, b'G') | (0, false, b'`') => {
                let x = (p(0, 1) - 1).clamp(0, self.cols as i32 - 1) as usize;
                self.move_x(x);
            }
            (0, false, b'd') => {
                let y = (p(0, 1) - 1).clamp(0, self.rows as i32 - 1) as usize;
                self.move_y(y);
            }
            (0, false, b'e') => {
                let n = p(0, 1) as usize;
                let y = (self.cur().y + n).min(self.rows.saturating_sub(1));
                self.move_y(y);
            }
            (0, false, b'a') => {
                let n = p(0, 1) as usize;
                let x = (self.cur().x + n).min(self.cols.saturating_sub(1));
                self.move_x(x);
            }
            // ── Erase ───────────────────────────────────────────────────
            (0, false, b'J') | (0, true, b'J') => {
                let r = self.cur().y;
                let c = self.cur().x;
                match p0(0, 0) {
                    0 => {
                        self.erase_cols(r, c, self.cols);
                        for row in r + 1..self.rows {
                            self.erase_row(row);
                        }
                    }
                    1 => {
                        for row in 0..r {
                            self.erase_row(row);
                        }
                        self.erase_cols(r, 0, c + 1);
                    }
                    2 | 3 => self.erase_screen(),
                    _ => {}
                }
            }
            (0, false, b'K') | (0, true, b'K') => {
                let r = self.cur().y;
                let c = self.cur().x;
                match p0(0, 0) {
                    0 => self.erase_cols(r, c, self.cols),
                    1 => self.erase_cols(r, 0, c + 1),
                    2 => self.erase_row(r),
                    _ => {}
                }
            }
            (0, false, b'X') => {
                let n = p(0, 1) as usize;
                let r = self.cur().y;
                let c = self.cur().x;
                self.erase_cols(r, c, c + n);
            }
            // ── Insert/Delete chars ──────────────────────────────────────
            (0, false, b'@') => {
                // ICH – insert blank chars (shift right)
                let n = p(0, 1) as usize;
                let r = self.cur().y;
                let c0 = self.cur().x;
                let cols = self.cols;
                let scr = &mut self.screens[self.alt];
                let limit = cols.saturating_sub(n);
                for c in (c0..limit).rev() {
                    scr[r * cols + c + n] = scr[r * cols + c];
                }
                let bg = self.attr.bg;
                for c in c0..(c0 + n).min(cols) {
                    scr[r * cols + c] = Cell::blank(eqnx::FOREGROUND, bg);
                }
            }
            (0, false, b'P') => {
                // DCH – delete chars (shift left), full Cell copy
                let n = p(0, 1) as usize;
                let r = self.cur().y;
                let c0 = self.cur().x;
                let cols = self.cols;
                let scr = &mut self.screens[self.alt];
                for c in c0..cols.saturating_sub(n) {
                    scr[r * cols + c] = scr[r * cols + c + n];
                }
                let bg = self.attr.bg;
                for c in cols.saturating_sub(n)..cols {
                    scr[r * cols + c] = Cell::blank(eqnx::FOREGROUND, bg);
                }
            }
            // ── Insert/Delete lines ───────────────────────────────────────
            (0, false, b'L') => {
                // IL – insert lines
                let n = p(0, 1) as usize;
                let r = self.cur().y;
                if r <= self.scroll_bottom {
                    self.scroll_down(r, n);
                }
                // cursor moves to left margin; y is already correct after scroll_down
                let cy = self.cur().y;
                self.move_to(0, cy);
            }
            (0, false, b'M') => {
                // DL – delete lines
                let n = p(0, 1) as usize;
                let r = self.cur().y;
                if r <= self.scroll_bottom {
                    self.scroll_up(r, n);
                }
                self.move_to(0, self.cur().y);
            }
            // ── Scroll ───────────────────────────────────────────────────
            (0, false, b'S') => {
                let n = p(0, 1) as usize;
                self.scroll_up(self.scroll_top, n);
            }
            (0, false, b'T') => {
                let n = p(0, 1) as usize;
                self.scroll_down(self.scroll_top, n);
            }
            // ── SGR ──────────────────────────────────────────────────────
            (0, false, b'm') => {
                self.apply_sgr();
            }
            // ── DECSTBM – Set scroll region ───────────────────────────────
            (0, false, b'r') => {
                let top = (p(0, 1) - 1).clamp(0, self.rows as i32 - 1) as usize;
                let bottom =
                    (p(1, self.rows as i32) - 1).clamp(top as i32, self.rows as i32 - 1) as usize;
                if top < bottom {
                    self.scroll_top = top;
                    self.scroll_bottom = bottom;
                } else {
                    self.scroll_top = 0;
                    self.scroll_bottom = self.rows.saturating_sub(1);
                }
                self.move_to(0, self.scroll_top);
            }
            // ── ANSI save/restore cursor (CSI s / CSI u) ─────────────────
            // Save into the "other" cursor slot (same trick as ESC 7/8).
            (0, false, b's') => {
                let cur = *self.cur();
                let other = 1 - self.alt;
                self.cursor[other] = cur;
            }
            (0, false, b'u') => {
                let other = 1 - self.alt;
                let saved = self.cursor[other];
                *self.cur_mut() = saved;
                self.clamp_cursor();
            }
            // ── DEC private modes (h = set, l = reset) ────────────────────
            (0, true, b'h') => {
                self.set_dec_mode(p0(0, 0), true);
            }
            (0, true, b'l') => {
                self.set_dec_mode(p0(0, 0), false);
            }
            // ── Device Status Report ──────────────────────────────────────
            (0, false, b'n') if p0(0, 0) == 6 => {
                // CPR – Cursor Position Report
                let row = self.cur().y + 1;
                let col = self.cur().x + 1;
                let mut buf = [0u8; 24];
                let mut pos = 0usize;
                buf[pos] = 0x1B;
                pos += 1;
                buf[pos] = b'[';
                pos += 1;
                pos += fmt_u32(&mut buf[pos..], row as u32);
                buf[pos] = b';';
                pos += 1;
                pos += fmt_u32(&mut buf[pos..], col as u32);
                buf[pos] = b'R';
                pos += 1;
                let _ = self.pty.write(&buf[..pos]);
            }
            // ── Primary Device Attributes ─────────────────────────────────
            (0, false, b'c') => {
                let _ = self.pty.write(b"\x1b[?1;0c");
            }
            // ── Window operations (XTWINOPS) ──────────────────────────────
            (0, false, b't') => {
                if p0(0, 0) == 18 {
                    let mut buf = [0u8; 32];
                    let mut pos = 0usize;
                    buf[pos] = 0x1B;
                    pos += 1;
                    buf[pos] = b'[';
                    pos += 1;
                    buf[pos] = b'8';
                    pos += 1;
                    buf[pos] = b';';
                    pos += 1;
                    pos += fmt_u32(&mut buf[pos..], self.rows as u32);
                    buf[pos] = b';';
                    pos += 1;
                    pos += fmt_u32(&mut buf[pos..], self.cols as u32);
                    buf[pos] = b't';
                    pos += 1;
                    let _ = self.pty.write(&buf[..pos]);
                }
            }
            // ── DECSCUSR – cursor shape (CSI Ps SP q) ────────────────────
            (b' ', false, b'q') => {
                self.modes.cursor_shape = match p0(0, 0) {
                    1 | 2 => 0, // block
                    3 | 4 => 3, // underline
                    5 | 6 => 5, // bar
                    _ => 0,
                };
            }
            // ── Tab stop clear ────────────────────────────────────────────
            (0, false, b'g') => {
                let col = self.cur().x;
                match p0(0, 0) {
                    0 => {
                        self.tab_stops[col] = false;
                    }
                    3 => {
                        self.tab_stops.fill(false);
                    }
                    _ => {}
                }
            }
            _ => {} // Unknown CSI – silently ignore
        }
    }

    fn set_dec_mode(&mut self, n: i32, val: bool) {
        match n {
            1 => self.modes.app_cursor = val,
            7 => self.modes.wrap = val,
            25 => self.modes.cursor_visible = val,
            1000 | 1002 | 1003 => self.modes.mouse = val,
            1047 => {
                if val {
                    self.enter_alt(false);
                } else {
                    self.exit_alt();
                }
            }
            1048 => {
                // Save or restore only the cursor position (no screen switch).
                // We use the same "other slot" trick as ESC 7/8 / CSI s/u.
                if val {
                    let cur = *self.cur();
                    let other = 1 - self.alt;
                    self.cursor[other] = cur;
                } else {
                    let other = 1 - self.alt;
                    let saved = self.cursor[other];
                    *self.cur_mut() = saved;
                    self.clamp_cursor();
                }
            }
            1049 => {
                if val {
                    self.enter_alt(true);
                } else {
                    self.exit_alt();
                }
            }
            _ => {}
        }
    }

    fn enter_alt(&mut self, clear: bool) {
        if self.alt == 1 {
            return;
        }
        // Save cursor into screen 0's slot (already there)
        self.alt = 1;
        if clear {
            self.erase_screen();
        }
        self.move_to(0, 0);
    }

    fn exit_alt(&mut self) {
        if self.alt == 0 {
            return;
        }
        self.alt = 0;
        // Cursor for screen 0 is already in cursor[0]
    }

    // ── Main byte-stream processor ────────────────────────────────────────

    fn write_bytes(&mut self, data: &[u8]) {
        for &b in data {
            self.feed(b);
        }
    }

    fn feed(&mut self, b: u8) {
        match self.parser.state {
            // ── Ground ────────────────────────────────────────────────────
            PState::Ground => {
                if b == 0x1B {
                    // ESC: abort any in-progress UTF-8 sequence
                    self.parser.utf8_rem = 0;
                    self.parser.utf8_cp = 0;
                    self.start_esc();
                } else if b < 0x20 || b == 0x7F {
                    self.handle_c0(b);
                } else {
                    // Printable: feed through UTF-8 decoder
                    if let Some(cp) = self.parser.utf8(b) {
                        // DEC Special Graphics translation
                        let cp = if self.cur().charset == 1 && cp >= 0x60 && cp <= 0x7E {
                            DEC_SPECIAL[(cp - 0x60) as usize]
                        } else {
                            cp
                        };
                        self.put_char(cp);
                    }
                }
            }

            // ── ESC ───────────────────────────────────────────────────────
            PState::Esc => {
                self.parser.state = PState::Ground;
                match b {
                    b'[' => {
                        self.parser.nparams = 0;
                        self.parser.cur = 0;
                        self.parser.inter = 0;
                        self.parser.priv_mode = false;
                        self.parser.state = PState::Csi;
                    }
                    b']' => {
                        self.parser.osc.clear();
                        self.parser.state = PState::OscStr;
                    }
                    b'(' | b')' => {
                        self.parser.state = PState::EscInter(b);
                    }
                    b'=' => {
                        self.modes.app_keypad = true;
                    }
                    b'>' => {
                        self.modes.app_keypad = false;
                    }
                    b'c' => {
                        self.full_reset();
                    }
                    b'7' => {
                        // DECSC
                        let sc = *self.cur();
                        // Save into the "saved" slot (cursor[alt] is the live one;
                        // we reuse a tiny struct trick: save x,y,attr in a scratch field)
                        // For simplicity, keep a dedicated saved cursor per screen.
                        // Here we snapshot cursor[alt] into a saved field.
                        // We store it in the *other* screen's cursor slot as scratch.
                        let other = 1 - self.alt;
                        self.cursor[other] = sc;
                    }
                    b'8' => {
                        // DECRC
                        let other = 1 - self.alt;
                        let saved = self.cursor[other];
                        *self.cur_mut() = saved;
                        self.clamp_cursor();
                    }
                    b'M' => {
                        // RI – Reverse Index
                        let cy = self.cur().y;
                        let top = self.scroll_top;
                        if cy == top {
                            self.scroll_down(top, 1);
                        } else {
                            self.cur_mut().y -= 1;
                        }
                        self.cur_mut().pending_wrap = false;
                    }
                    b'D' => {
                        // IND – Index
                        self.do_lf();
                    }
                    b'E' => {
                        // NEL – Next Line
                        self.cur_mut().x = 0;
                        self.do_lf();
                    }
                    b'H' => {
                        // HTS – Horizontal Tab Set
                        let x = self.cur().x;
                        self.tab_stops[x] = true;
                    }
                    _ => {} // Unknown ESC – ignore
                }
            }

            // ── ESC intermediate byte (charset designator) ────────────────
            PState::EscInter(inter) => {
                self.parser.state = PState::Ground;
                match (inter, b) {
                    (b'(', b'B') | (b')', b'B') => {
                        self.cur_mut().charset = 0;
                    }
                    (b'(', b'0') | (b')', b'0') => {
                        self.cur_mut().charset = 1;
                    }
                    _ => {}
                }
            }

            // ── CSI ───────────────────────────────────────────────────────
            PState::Csi => {
                if b >= b'0' && b <= b'9' {
                    // Accumulate digit
                    self.parser.cur = self.parser.cur.saturating_mul(10) + (b - b'0') as i32;
                } else if b == b';' {
                    // Parameter separator: commit current
                    self.parser.commit_param();
                } else if b == b'?' {
                    // Private mode prefix
                    self.parser.priv_mode = true;
                } else if b >= 0x20 && b <= 0x2F {
                    // Intermediate byte (e.g. space 0x20 before 'q' in DECSCUSR)
                    self.parser.inter = b;
                } else if b >= 0x40 && b <= 0x7E {
                    // Final byte: dispatch
                    self.execute_csi(b);
                    self.parser.state = PState::Ground;
                } else {
                    // Illegal in CSI – abort
                    self.parser.state = PState::Ground;
                }
            }

            // ── OSC string ────────────────────────────────────────────────
            PState::OscStr => {
                if b == 0x07 {
                    // BEL terminates OSC
                    self.parser.osc.clear();
                    self.parser.state = PState::Ground;
                } else if b == 0x1B {
                    // Might be ESC \ (ST)
                    self.parser.state = PState::OscMaybeSt;
                } else if self.parser.osc.len() < 512 {
                    self.parser.osc.push(b);
                }
                // If osc buffer full, keep consuming until terminator
            }

            // ── OSC: saw ESC, waiting for '\' (ST) ────────────────────────
            PState::OscMaybeSt => {
                if b == b'\\' {
                    // ESC \ = String Terminator: clean end
                    self.parser.osc.clear();
                    self.parser.state = PState::Ground;
                } else {
                    // Not ST: treat ESC as a new escape sequence
                    self.parser.osc.clear();
                    self.start_esc();
                    // Re-process `b` in ESC state by recursing once (safe: no loop)
                    if self.parser.state == PState::Esc {
                        self.parser.state = PState::Ground;
                        self.feed_esc_byte(b);
                    }
                }
            }
        }
    }

    fn start_esc(&mut self) {
        self.parser.state = PState::Esc;
    }

    /// Process a byte in ESC state (used to re-process after OscMaybeSt).
    fn feed_esc_byte(&mut self, b: u8) {
        // Temporarily set Esc state, feed the byte
        self.parser.state = PState::Esc;
        self.feed(b);
    }

    // ── C0 control character handler ──────────────────────────────────────

    fn handle_c0(&mut self, b: u8) {
        match b {
            b'\r' => {
                self.cur_mut().x = 0;
                self.cur_mut().pending_wrap = false;
            }
            b'\n' | 0x0B | 0x0C => {
                // LF / VT / FF: linefeed.  Does NOT reset column.
                self.do_lf();
            }
            0x08 => {
                // BS
                let x = self.cur().x;
                if x > 0 {
                    self.cur_mut().x = x - 1;
                }
                self.cur_mut().pending_wrap = false;
            }
            0x09 => {
                // HT – horizontal tab
                let x = self.cur().x;
                let cols = self.cols;
                let mut next = x + 1;
                while next < cols && !self.tab_stops[next] {
                    next += 1;
                }
                self.cur_mut().x = next.min(cols.saturating_sub(1));
                self.cur_mut().pending_wrap = false;
            }
            0x07 => {
                self.bell = true;
            }
            0x7F => {} // DEL – ignore
            _ => {}    // Other C0 – ignore
        }
    }

    // ── Render ────────────────────────────────────────────────────────────
    //
    // We call window_set() per cell, never window_puts().
    //
    // Reason: window_puts(w, x, y, fg, bg, str) iterates bytes with x+i
    // as the column index.  For ASCII strings this is correct (1 byte = 1
    // column = 1 char), but our cell buffer already stores decoded Unicode
    // codepoints.  Using window_set directly gives us:
    //   1. Correct column placement for every codepoint
    //   2. Full Unicode support (box drawing, CJK, emoji) without re-encoding
    //   3. Simpler code with no UTF-8 encode/decode round-trip

    fn draw(&mut self, win: *mut eqnx::Window) {
        // Clear background (BACKGROUND, BACKGROUND as per eqnx convention)
        unsafe {
            eqnx::window_clear(win, eqnx::BACKGROUND, eqnx::BACKGROUND);
        }

        if self.bell {
            // Flash: invert fg/bg for one frame
            unsafe {
                eqnx::window_clear(win, eqnx::BACKGROUND, eqnx::FOREGROUND);
            }
            self.bell = false;
        }

        // Draw cells
        for r in 0..self.rows {
            for c in 0..self.cols {
                let cell = self.screens[self.alt][r * self.cols + c];

                // Skip wide-char right halves (they share the glyph with col-1)
                if cell.flags & CELL_WIDE_RIGHT != 0 {
                    continue;
                }

                let ch = if cell.ch == 0 { b' ' as u32 } else { cell.ch };

                unsafe {
                    eqnx::window_set(win, c as i32, r as i32, ch, cell.fg, cell.bg);
                }
            }
        }

        // Draw cursor overlay
        if self.modes.cursor_visible {
            let cx = self.cur().x;
            let cy = self.cur().y;
            if cx < self.cols && cy < self.rows {
                // If on a wide-right cell, shift left to get the real cell's colors
                let cell = {
                    let raw = self.screens[self.alt][cy * self.cols + cx];
                    if raw.flags & CELL_WIDE_RIGHT != 0 && cx > 0 {
                        self.screens[self.alt][cy * self.cols + cx - 1]
                    } else {
                        raw
                    }
                };

                // Guarantee cursor visibility: if fg == bg (blank cell), use defaults
                let (cur_fg, cur_bg) = if cell.fg == cell.bg {
                    (eqnx::FOREGROUND, eqnx::BACKGROUND)
                } else {
                    (cell.bg, cell.fg) // inverted
                };

                let cp = match self.modes.cursor_shape {
                    3 | 4 => 0x2581u32, // ▁ underline
                    5 | 6 => 0x258Cu32, // ▌ bar
                    _ => b' ' as u32,   // block (space with reversed colors)
                };

                unsafe {
                    eqnx::window_set(win, cx as i32, cy as i32, cp, cur_fg, cur_bg);
                }
            }
        }
    }
}

// ──────────────────────────────────────────────────────────────────────────────
// Small helpers
// ──────────────────────────────────────────────────────────────────────────────

/// Write a decimal u32 into a byte slice; returns number of bytes written.
fn fmt_u32(buf: &mut [u8], mut n: u32) -> usize {
    if n == 0 {
        if !buf.is_empty() {
            buf[0] = b'0';
        }
        return 1;
    }
    let mut d = 0usize;
    let mut tmp = n;
    while tmp > 0 {
        d += 1;
        tmp /= 10;
    }
    if d > buf.len() {
        return 0;
    }
    for i in (0..d).rev() {
        buf[i] = b'0' + (n % 10) as u8;
        n /= 10;
    }
    d
}

// ──────────────────────────────────────────────────────────────────────────────
// Global state – single TERM pointer, all eqnx callbacks route through it
// ──────────────────────────────────────────────────────────────────────────────

#[unsafe(no_mangle)]
pub static mut self_window: *mut eqnx::Window = ptr::null_mut();

#[unsafe(no_mangle)]
pub static mut self_plugin: *mut eqnx::Plugin = ptr::null_mut();

/// The single global terminal instance.  Box avoids placing multi-MB screen
/// buffers on the stack.
static mut TERM: Option<Box<Term>> = None;

/// Safety: called only from the single eqnx event-loop thread.
/// Uses raw pointer to satisfy the Edition 2024 `static_mut_refs` lint
/// (no & or &mut taken from the static directly).
///
/// Returns `None` before `main()` has run (eqnx fires an initial `resize()`
/// before the plugin `main()` executes), so callers can early-return.
#[inline]
unsafe fn try_term() -> Option<&'static mut Term> {
    let p = core::ptr::addr_of_mut!(TERM);
    match *p {
        Some(ref mut b) => Some(b.as_mut()),
        None => None,
    }
}

// ──────────────────────────────────────────────────────────────────────────────
// Raw Linux x86-64 syscalls
// ──────────────────────────────────────────────────────────────────────────────

const TIOCSWINSZ: u64 = 0x5414;
const SYS_IOCTL: i64 = 16;
const SYS_FCNTL: i64 = 72;
const F_GETFL: i64 = 3;
const F_SETFL: i64 = 4;
const O_NONBLOCK: i64 = 2048;

unsafe fn set_nonblock(fd: i32) {
    let flags: i64;
    core::arch::asm!(
        "syscall",
        in("rax") SYS_FCNTL, in("rdi") fd as i64, in("rsi") F_GETFL, in("rdx") 0i64,
        out("rcx") _, out("r11") _, lateout("rax") flags,
    );
    core::arch::asm!(
        "syscall",
        in("rax") SYS_FCNTL, in("rdi") fd as i64, in("rsi") F_SETFL,
        in("rdx") flags | O_NONBLOCK,
        out("rcx") _, out("r11") _, lateout("rax") _,
    );
}

unsafe fn set_winsize(fd: i32, rows: i32, cols: i32) {
    let ws: [u16; 4] = [rows as u16, cols as u16, 0, 0];
    core::arch::asm!(
        "syscall",
        in("rax") SYS_IOCTL, in("rdi") fd as i64, in("rsi") TIOCSWINSZ as i64,
        in("rdx") &ws as *const [u16; 4] as i64,
        out("rcx") _, out("r11") _, lateout("rax") _,
    );
}

// Modifier bitmasks from src/keypress.h
const MOD_CONTROL: u32 = 0xC;
const MOD_ALT: u32 = 0x300;

// ──────────────────────────────────────────────────────────────────────────────
// eqnx plugin callbacks
// ──────────────────────────────────────────────────────────────────────────────

#[unsafe(no_mangle)]
extern "C" fn resize(x: i32, y: i32, w: i32, h: i32) -> i32 {
    unsafe {
        let mut cx = 0i32;
        let mut cy = 0i32;
        let mut cw = 0i32;
        let mut ch = 0i32;
        eqnx::window_px_to_coords(x, y, &mut cx, &mut cy);
        eqnx::window_px_to_coords(w, h, &mut cw, &mut ch);

        let new_cols = (cw - cx) as usize;
        let new_rows = (ch - cy) as usize;
        if new_rows < 1 || new_cols < 1 {
            return 0;
        }

        let Some(t) = try_term() else { return 0; };
        t.resize(new_rows, new_cols);

        // Notify PTY
        let fd = t.pty.as_raw_fd();
        set_winsize(fd, new_rows as i32, new_cols as i32);
    }
    0
}

#[unsafe(no_mangle)]
extern "C" fn kp_event(sym: i32, mods: i32) -> i32 {
    unsafe {
        let Some(t) = try_term() else { return 0; };
        let mods = mods as u32;
        let ctrl = mods & MOD_CONTROL != 0;
        let alt = mods & MOD_ALT != 0;
        let app_c = t.modes.app_cursor;

        let handled = match sym as u32 {
            eqnx::XKB_KEY_Return => t.pty.write(b"\r").is_ok(),
            eqnx::XKB_KEY_KP_Enter => {
                if t.modes.app_keypad {
                    t.pty.write(b"\x1bOM").is_ok()
                } else {
                    t.pty.write(b"\r").is_ok()
                }
            }
            eqnx::XKB_KEY_BackSpace => t.pty.write(b"\x7f").is_ok(),
            eqnx::XKB_KEY_Tab => t.pty.write(b"\t").is_ok(),
            eqnx::XKB_KEY_Escape => t.pty.write(b"\x1b").is_ok(),
            eqnx::XKB_KEY_Delete => t.pty.write(b"\x1b[3~").is_ok(),
            eqnx::XKB_KEY_Insert => t.pty.write(b"\x1b[2~").is_ok(),
            eqnx::XKB_KEY_Left => t
                .pty
                .write(if app_c { b"\x1bOD" } else { b"\x1b[D" })
                .is_ok(),
            eqnx::XKB_KEY_Right => t
                .pty
                .write(if app_c { b"\x1bOC" } else { b"\x1b[C" })
                .is_ok(),
            eqnx::XKB_KEY_Up => t
                .pty
                .write(if app_c { b"\x1bOA" } else { b"\x1b[A" })
                .is_ok(),
            eqnx::XKB_KEY_Down => t
                .pty
                .write(if app_c { b"\x1bOB" } else { b"\x1b[B" })
                .is_ok(),
            eqnx::XKB_KEY_Home => t.pty.write(b"\x1b[H").is_ok(),
            eqnx::XKB_KEY_End => t.pty.write(b"\x1b[F").is_ok(),
            eqnx::XKB_KEY_Prior => t.pty.write(b"\x1b[5~").is_ok(),
            eqnx::XKB_KEY_Next => t.pty.write(b"\x1b[6~").is_ok(),
            eqnx::XKB_KEY_F1 => t.pty.write(b"\x1bOP").is_ok(),
            eqnx::XKB_KEY_F2 => t.pty.write(b"\x1bOQ").is_ok(),
            eqnx::XKB_KEY_F3 => t.pty.write(b"\x1bOR").is_ok(),
            eqnx::XKB_KEY_F4 => t.pty.write(b"\x1bOS").is_ok(),
            eqnx::XKB_KEY_F5 => t.pty.write(b"\x1b[15~").is_ok(),
            eqnx::XKB_KEY_F6 => t.pty.write(b"\x1b[17~").is_ok(),
            eqnx::XKB_KEY_F7 => t.pty.write(b"\x1b[18~").is_ok(),
            eqnx::XKB_KEY_F8 => t.pty.write(b"\x1b[19~").is_ok(),
            eqnx::XKB_KEY_F9 => t.pty.write(b"\x1b[20~").is_ok(),
            eqnx::XKB_KEY_F10 => t.pty.write(b"\x1b[21~").is_ok(),
            eqnx::XKB_KEY_F11 => t.pty.write(b"\x1b[23~").is_ok(),
            eqnx::XKB_KEY_F12 => t.pty.write(b"\x1b[24~").is_ok(),
            _ => false,
        };

        if !handled {
            // xkb_keysym_to_utf8 returns the number of bytes written INCLUDING
            // the NUL terminator.  For 'a' it returns 2 (0x61, 0x00).  We must
            // use n-1 to strip the NUL, otherwise every keystroke sends a NUL
            // byte to the shell.
            let mut buf = [0u8; 8];
            let raw_n = eqnx::xkb_keysym_to_utf8(sym as u32, buf.as_mut_ptr() as *mut i8, buf.len());
            let n = if raw_n > 0 { (raw_n - 1) as usize } else { 0 };

            if ctrl && sym >= 0x20 && sym <= 0x7F {
                // Ctrl+key: send the control code (sym & 0x1F)
                if alt { let _ = t.pty.write(b"\x1b"); }
                let _ = t.pty.write(&[(sym & 0x1f) as u8]);
            } else if n > 0 {
                // Normal printable character(s)
                if alt { let _ = t.pty.write(b"\x1b"); }
                let _ = t.pty.write(&buf[..n]);
            }
        }

        let _ = t.pty.flush();
        eqnx::ask_for_redraw();
    }
    0
}

#[unsafe(no_mangle)]
extern "C" fn pointer_event(e: eqnx::Pointer_Event) -> i32 {
    unsafe {
        let Some(t) = try_term() else { return 0; };
        if !t.modes.mouse {
            return 0;
        }

        let x = (e.__bindgen_anon_2.x.max(0).min(t.cols as i32 - 1)) + 1;
        let y = (e.__bindgen_anon_2.y.max(0).min(t.rows as i32 - 1)) + 1;

        let mut buf = [0u8; 32];
        let mut pos = 0usize;
        buf[pos] = 0x1B;
        pos += 1;
        buf[pos] = b'[';
        pos += 1;
        buf[pos] = b'<';
        pos += 1;

        let (cb, release) = match e.type_ {
            t if t == eqnx::Pointer_Event_Pointer_Press => {
                (e.__bindgen_anon_1.btn.max(0).min(2), false)
            }
            t if t == eqnx::Pointer_Event_Pointer_Release => {
                (e.__bindgen_anon_1.btn.max(0).min(2), true)
            }
            t if t == eqnx::Pointer_Event_Pointer_Scroll => {
                let cb = if e.__bindgen_anon_1.scroll > 0 {
                    64
                } else {
                    65
                };
                (cb, false)
            }
            _ => return 0,
        };

        pos += fmt_u32(&mut buf[pos..], cb as u32);
        buf[pos] = b';';
        pos += 1;
        pos += fmt_u32(&mut buf[pos..], x as u32);
        buf[pos] = b';';
        pos += 1;
        pos += fmt_u32(&mut buf[pos..], y as u32);
        buf[pos] = if release { b'm' } else { b'M' };
        pos += 1;

        let _ = t.pty.write(&buf[..pos]);
        let _ = t.pty.flush();
    }
    0
}

#[unsafe(no_mangle)]
extern "C" fn render() -> i32 {
    unsafe {
        let Some(t) = try_term() else { return 0; };
        let win = self_window;

        // Read all available PTY data using raw libc::read().
        //
        // Why not Master::read()?  The pty crate's Read impl returns Ok(0)
        // on ANY error (including EAGAIN/EWOULDBLOCK), so the WouldBlock
        // check never fires and we can't distinguish "no data" from "EOF".
        // Using libc::read directly lets us see the actual errno.
        let fd = t.pty.as_raw_fd();
        let mut buf = [0u8; 4096];
        loop {
            let ret = libc::read(fd, buf.as_mut_ptr() as *mut libc::c_void, buf.len());
            if ret > 0 {
                t.write_bytes(&buf[..ret as usize]);
            } else {
                // ret == 0: EOF, ret == -1: error (EAGAIN/EWOULDBLOCK = no data)
                break;
            }
        }

        t.draw(win);
    }
    0
}

#[unsafe(no_mangle)]
extern "C" fn main(_argc: i32, _argv: *const *const i8) -> i32 {
    // Fork PTY + shell
    let master = create_pty();

    unsafe {
        // We don't know the real size yet – use a placeholder; resize() will
        // fire immediately after mainloop() returns control to eqnx.
        let t = Term::new(24, 80, master);
        let fd = t.pty.as_raw_fd();
        set_winsize(fd, 24, 80);
        set_nonblock(fd);
        // Register the PTY fd so eqnx wakes us on output
        eqnx::listen_to_fd(fd);

        core::ptr::addr_of_mut!(TERM).write(Some(t));
        eqnx::mainloop();
    }
    0
}

// ──────────────────────────────────────────────────────────────────────────────
// PTY / fork helpers
// ──────────────────────────────────────────────────────────────────────────────

fn create_pty() -> Master {
    let shell = env::var("SHELL").unwrap_or_else(|_| "/bin/sh".to_string());

    let fork = Fork::from_ptmx().unwrap_or_else(|e| {
        eprintln!("Fork::from_ptmx() failed: {e}");
        std::process::exit(1);
    });

    match fork.is_parent() {
        Ok(master) => {
            // CRITICAL: Fork::drop() calls close() on the Master fd.
            // Master is #[derive(Copy, Clone)] so is_parent() returns a
            // *clone* (just copies the raw fd number, no dup()).  When
            // `fork` goes out of scope, Drop closes the fd — leaving our
            // cloned Master with a dangling fd number.  The kernel then
            // reassigns that fd number to the next open() (Wayland memfd),
            // and we end up reading framebuffer pixels instead of PTY data.
            // mem::forget prevents the Drop from running.
            mem::forget(fork);
            master
        }
        Err(_) => {
            // Child: exec the shell directly.
            let mut cmd = Command::new(&shell);
            cmd.env("TERM", "xterm-256color");
            let err = cmd.status();
            match err {
                Ok(s) => std::process::exit(s.code().unwrap_or(0)),
                Err(e) => {
                    eprintln!("exec '{shell}' failed: {e}");
                    std::process::exit(1);
                }
            }
        }
    }
}
