#!/bin/bash
# autogenerated eqnx run script for:
# - eqnx: ./eqnx
# - prog: rust_template/template.esx
# - conf: ./config.lua
# - psrc: rust_template/target/debug/
# - root: $HOME

HERE="/home/hugo/code/eqnx"
EQNX="$(which "./eqnx" || echo "$HERE/./eqnx")"
PROG="$HERE/rust_template/template.esx"
CONF="$HERE/./config.lua"
PSRC="$HERE/rust_template/target/debug/"

# Change cwd to root
cd "$HOME"

# Run
"$EQNX" -p "$PROG" -c "$CONF" -s "$PSRC"
